export const JOB_TYPE_LOAD_REQUEST = "JOB_TYPE_LOAD_REQUEST";
export const JOB_TYPE_LOAD_SUCCESS = "JOB_TYPE_LOAD_SUCCESS";
export const JOB_TYPE_LOAD_FAIL = "JOB_TYPE_LOAD_FAIL";
export const JOB_TYPE_LOAD_RESET = "JOB_TYPE_LOAD_RESET";

export const JOB_LOAD_SINGLE_REQUEST = "JOB_LOAD_SINGLE_REQUEST";
export const JOB_LOAD_SINGLE_SUCCESS = "JOB_LOAD_SINGLE_SUCCESS";
export const JOB_LOAD_SINGLE_FAIL = "JOB_LOAD_SINGLE_FAIL";
export const JOB_LOAD_SINGLE_RESET = "JOB_LOAD_SINGLE_RESET";

export const USER_APPLY_JOB_REQUEST = "USER_APPLY_JOB_REQUEST";
export const USER_APPLY_JOB_SUCCESS = "USER_APPLY_JOB_SUCCESS";
export const USER_APPLY_JOB_FAIL = "USER_APPLY_JOB_FAIL";
export const USER_APPLY_JOB_RESET = "USER_APPLY_JOB_RESET";
